### ISSUE TITLE
GSoC Project Log

### ISSUE THREAD

**Issue by Marlin-Na** [Marlin-Na/TnT#1]
# June 9th

## Summary of current work

As for June 9, the package has a basic mechanism to construct JSCascade and convert it to a TnT browser, rewritten with S4.

In the last commit, I rethink about the structure of each track class and include implementation of certain types. in the current design, each track contains a slot of virtual class "TrackData" which has sub-classes like "RangeTrackData", "PosTrackData", "TxDbTrackData".

Each type of track will have methods to compile into javascript, with regard to the slot of "TrackData" and two other slots "Spec" and "Display". I am currently designing the structure of "Browser" class that holds all the tracks and methods to prepare the tracks before converting to JavaScript (include tasks to summarize the genome, chromosome (i.e. seqlevels) and ranges from list of tracks).

The most important task for now is to make the browser usable as soon as possible, expected before **June 13**, then I will come back to tidy code and implement other types of track.

## Tasks

- [x] Implement Gene Track
- [x] Implement prototypes of "TnTBoard" class and associated methods.

Then:
- [ ] Implement Transcript Track

Overall, I should quickly make the TnT browser usable, then find possible suggestions from Toby and Miguel.

**Comment by Marlin-Na** [comment]
# June 15
## Current Features

A basic framework to construct and render tnt board has been implemented. A showcase and some explanation can be found in the following attachment. [Update Notes.zip](https://github.com/Marlin-Na/TnT/files/1078095/Update.Notes.zip)

## Next-step

- [ ] Provide transcript track and provide other types of track.
- [ ] Display tooltips.
- [x] The size/width of the board should to be responsive, the height of container in knitr should be automatically set.
- [ ] Implement TnT Genome class, which should inherit the TnT Board class.
- [ ] Improve the printing method of TnTBoard, so that it can be directly rendered under shiny and rmarkdown.
- [ ] Informative show method for tracks and track data.

**Comment by Marlin-Na** [comment]
GSoC 2017 has been finished, close.
